#!/usr/bin/env python3

import os
import time

import praw


class RedditBotBase(object):
    def __init__(self):
        self.flair = None
        self.user_agent = f"{os.getenv('BOT_NAME')} | {os.getenv('VERSION')} | By {os.getenv('DEVELOPER')}"
        self.subreddit = os.getenv("SUBREDDIT")
        self.xpost_subreddit = os.getenv("XPOST_SUBREDDIT")
        self.delay = os.getenv("DELAY")
        self.reddit = praw.Reddit(
            client_id=os.getenv("CLIENT_ID"),
            client_secret=os.getenv("CLIENT_SECRET"),
            username=os.getenv("USERNAME"),
            password=os.getenv("PASSWORD"),
            user_agent=self.user_agent,
        )

        print(f"Starting up... {self.user_agent}")


class XPostByKarmaThreshold(RedditBotBase):
    def __init__(self):
        super().__init__()
        self.karma_threshold = os.getenv("KARMA_THRESHOLD")

    def main(self):
        while True:
            print(f"{self.user_agent} is running...")
            for submission in self.reddit.subreddit(self.subreddit).stream.submissions(pause_after=1):
                if submission is None:
                    break
                karma = submission.author.comment_karma + submission.author.link_karma
                
                if karma < self.karma_threshold:
                    submission.crosspost(self.xpost_subreddit, title=f"{submission.title}")

            time.sleep(int(self.delay))


if __name__ == "__main__":
    b = XPostByKarmaThreshold()
    b.main()
